# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!


target 'LocalSearchTemp' do

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end
end


pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'BBlock'
pod 'Google/SignIn'
#pod 'TGLParallaxCarousel'
pod 'SwiftCarousel'

end

